//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncAppGUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pathGridMember", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class pathGridMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutoSyncField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SyncTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoSync {
            get {
                return this.AutoSyncField;
            }
            set {
                if ((this.AutoSyncField.Equals(value) != true)) {
                    this.AutoSyncField = value;
                    this.RaisePropertyChanged("AutoSync");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SFolder {
            get {
                return this.SFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.SFolderField, value) != true)) {
                    this.SFolderField = value;
                    this.RaisePropertyChanged("SFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SyncType {
            get {
                return this.SyncTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SyncTypeField, value) != true)) {
                    this.SyncTypeField = value;
                    this.RaisePropertyChanged("SyncType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TFolder {
            get {
                return this.TFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.TFolderField, value) != true)) {
                    this.TFolderField = value;
                    this.RaisePropertyChanged("TFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        SyncAppGUI.ServiceReference1.pathGridMember[] GetData(SyncAppGUI.ServiceReference1.pathGridMember[] folderPairs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<SyncAppGUI.ServiceReference1.pathGridMember[]> GetDataAsync(SyncAppGUI.ServiceReference1.pathGridMember[] folderPairs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SyncAppGUI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SyncAppGUI.ServiceReference1.IService1>, SyncAppGUI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SyncAppGUI.ServiceReference1.pathGridMember[] GetData(SyncAppGUI.ServiceReference1.pathGridMember[] folderPairs) {
            return base.Channel.GetData(folderPairs);
        }
        
        public System.Threading.Tasks.Task<SyncAppGUI.ServiceReference1.pathGridMember[]> GetDataAsync(SyncAppGUI.ServiceReference1.pathGridMember[] folderPairs) {
            return base.Channel.GetDataAsync(folderPairs);
        }
    }
}
